#!/bin/bash

set -e

_echo() { echo -e "\e[1m==> $@\e[0m"; }
_info() { echo -e "\e[36m  -> $@\e[0m"; }

if [ $UID -ne 0 ]; then
    echo -e "Please, run this script with sudo!"
    exit 1
fi


# === SKEL ===

_echo "Setting up skel ..."

_info "/etc/skel/.bashrc"

cat << EOF > /etc/skel/.bashrc
#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ \$- != *i* ]] && return

# set history size
HISTSIZE=1000

# prevent duplicates
HISTCONTROL=ignoreboth

# append to the history instead of overwriting
shopt -s histappend

# check terminal window size to update $LINES and $COLUMNS
shopt -s checkwinsize

# enable colors
case "\$TERM" in
  xterm-color|*-256color)
    alias ls='ls --color=auto --group-directories-first'

    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
    alias ip='ip --color=auto'
    alias tree='tree -C'
    ;;
esac

# prompt
PS1='\[\e[1;96m\]\u\[\e[0m\]@\[\e[1;93m\]\h\[\e[0m\] [\[\e[32m\]\w\[\e[0m\]] \\\$ '

# ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# load profile definitions
[[ -f ~/.bash_profile ]] && . ~/.bash_profile

# load bash aliases
[[ -f ~/.bash_aliases ]] && . ~/.bash_aliases
EOF

_info "/etc/skel/.bash_profile"

cat << EOF > /etc/skel/.bash_profile
DIFFPROG=nano
EDITOR=nano
EOF

_info "/etc/skel/.bash_logout"

cat << EOF > /etc/skel/.bash_logout
#
# ~/.bash_logout
#
EOF


# === ROOT BASHRC ===

_echo "Setting up root's bashrc ..."

_info "/root/.bashrc"

cat << EOF > /root/.bashrc
#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ \$- != *i* ]] && return

# set history size
HISTSIZE=1000

# prevent duplicates
HISTCONTROL=ignoreboth

# append to the history instead of overwriting
shopt -s histappend

# check terminal window size to update $LINES and $COLUMNS
shopt -s checkwinsize

# enable colors
case "\$TERM" in
  xterm-color|*-256color)
    alias ls='ls --color=auto --group-directories-first'

    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
    alias ip='ip --color=auto'
    alias tree='tree -C'
    ;;
esac

# prompt
PS1='\[\e[1;31m\]\u\[\e[0m\]@\[\e[1;33m\]\h\[\e[0m\] [\[\e[32m\]\w\[\e[0m\]] \\\$ '

# ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# load profile definitions
[[ -f ~/.bash_profile ]] && . ~/.bash_profile

# load bash aliases
[[ -f ~/.bash_aliases ]] && . ~/.bash_aliases
EOF


# === SYSCTL ===

_echo "Setting up sysctl ..."

_info "/etc/sysctl.d/10-default.conf"

cat << EOF > /etc/sysctl.d/10-default.conf
# Reduce tendency to swap
vm.swappiness = 10

# Reduce tendency to reclaim cache memory
vm.vfs_cache_pressure = 50

# Controls the number of pages read from swap at once. Defaults to 3.
# Recommended: 1 page for swaps in SSD and 2 pages for swaps in HDD.
vm.page-cluster = 0

# Increase network device queue. May prevent packet loss.
net.core.netdev_max_backlog = 4096

# Disable Watchdog. This reduces boot and shutdown times. Not good for servers!
kernel.nmi_watchdog = 0
EOF


# === UDEV RULES ===

_echo "Setting up UDEV rules ..."

_info "/etc/udev/rules.d/40-hpet-permissions.rules"

cat << EOF > /etc/udev/rules.d/40-hpet-permissions.rules
KERNEL=="rtc0", GROUP="audio"
KERNEL=="hpet", GROUP="audio"
EOF

_info "/etc/udev/rules.d/60-ioschedulers.rules"

cat << EOF > /etc/udev/rules.d/60-ioschedulers.rules
# HDD
ACTION=="add|change", KERNEL=="sd[a-z]*", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"

# SSD
ACTION=="add|change", KERNEL=="sd[a-z]*|mmcblk[0-9]*", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="mq-deadline"

# NVMe SSD
ACTION=="add|change", KERNEL=="nvme[0-9]*", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="none"
EOF

_info "/etc/udev/rules.d/99-cpu-dma-latency.rules"

cat << EOF > /etc/udev/rules.d/99-cpu-dma-latency.rules
DEVPATH=="devices/virtual/misc/cpu_dma_latency", OWNER="root", GROUP="audio", MODE="0660"
EOF


# === ENVIRONMENT VARIABLES ===

_echo "Setting up environment variables ..."

_info "/etc/environment.d"

mkdir -p /etc/environment.d

_info "/etc/environment.d/30-mesa-opencl.conf"

cat << EOF > /etc/environment.d/30-mesa-opencl.conf
RUSTICL_ENABLE=radeonsi
EOF

_info "/etc/environment.d/30-rocm.conf"

cat << EOF > /etc/environment.d/30-rocm.conf
HSA_OVERRIDE_GFX_VERSION=10.3.0
EOF

_info "/etc/environment.d/30-vdpau.conf"

cat << EOF > /etc/environment.d/30-vdpau.conf
VDPAU_DRIVER=radeonsi
EOF


# === SYSTEMD-RESOLVED  ===

_echo "Setting up systemd-resolved ..."

_info "/etc/systemd/resolved.conf.d"

mkdir -p /etc/systemd/resolved.conf.d

_info "/etc/systemd/resolved.conf.d/default.conf"

cat << EOF > /etc/systemd/resolved.conf.d/default.conf
[Resolve]
Cache=yes
ReadEtcHosts=yes
StaleRetentionSec=604800
EOF

_info "systemctl enable --now systemd-resolved.service"

systemctl enable --now systemd-resolved.service


# === SUDO ===

_echo "Setting up sudo ..."

_info "/etc/sudoers.d/10_default"

cat << EOF > /etc/sudoers.d/10_default
# Allow users of group 'wheel' to use sudo
%wheel ALL=(ALL:ALL) ALL

# Enable password feedback (shows *** when typing password)
Defaults pwfeedback
EOF

_info "/etc/sudoers.d/90_scxctl"

cat << EOF > /etc/sudoers.d/90_scxctl
# Allow users of group 'wheel' to use scxctl without asking password
%wheel ALL=(ALL) NOPASSWD: /usr/bin/scxctl
EOF


# === USER XDG DIRECTORIES ===

_echo "Adding up user XDG directories (PATH/XDG_DATA_DIRS) ..."

_info "/etc/profile.d/xx-usr-xdg-dirs.sh"

cat << EOF > /etc/profile.d/xx-usr-xdg-dirs.sh
#!/bin/bash

# Add user binaries to PATH
append_path "\$HOME/.local/bin"

# Add user desktop shortcuts to XDG_DATA_DIRS
export XDG_DATA_DIRS="\$XDG_DATA_DIRS:\$HOME/.local/share/applications"
EOF


# === KERNEL CMDLINE ===

_echo "Setting up video mode in kernel command-line (UKI-only) ..."

_info "/etc/cmdline.d"

mkdir -p /etc/cmdline.d

_info "/etc/cmdline.d/11-video.conf"

cat << EOF > /etc/cmdline.d/11-video.conf
video=DP-1:1920x1080@200
EOF


# === KERNEL MODULES ===

_echo "Setting up kernel modules ..."

_info "/etc/modules-load.d/ntsync.conf"

cat << EOF > /etc/modules-load.d/ntsync.conf
ntsync
EOF


# === SCX SCHEDULERS ===

_echo "Installing scx-scheds and scx-tools ..."

_info "pacman -S --noconfirm scx-scheds scx-tools"

pacman -S --noconfirm scx-scheds scx-tools


# === GAMEMODE ===

_echo "Setting up Game Mode ..."

_info "pacman -S --noconfirm gamemode"

pacman -S --noconfirm gamemode

_info "systemctl --global enable gamemoded.service"

systemctl --global enable gamemoded.service

_info "/etc/gamemode.ini"

cat << EOF > /etc/gamemode.ini
[custom]
start=sudo scxctl start --sched lavd
end=sudo scxctl stop
EOF


# ===///===

_echo "Done"
