#! /bin/sh

if ! command -v docker &> /dev/null; then
    echo -e "\e[1mERROR\e[0m: docker is not installed"
    exit 1
fi


echo -e "\e[1m==> Pulling ollama/ollama:rocm ...\e[0m"
docker pull ollama/ollama:rocm

echo -e "\e[1m==> Stopping ollama ...\e[0m"
docker stop ollama

echo -e "\e[1m==> Updating ollama ...\e[0m"
docker rm ollama
docker run -d \
    --device /dev/kfd \
    --device /dev/dri \
    -v ollama:/root/.ollama \
    -p 11434:11434 \
    -e OLLAMA_VULKAN=1 \
    --name ollama \
    --restart always \
    ollama/ollama:rocm

echo -e "\e[1m==> Done\e[0m"
