#!/bin/bash

set -e

if ! command -v docker &> /dev/null; then
    echo "ERROR: docker is not installed."
    exit 1
fi

if ! docker exec -i ollama ollama -v &> /dev/null; then
    docker start ollama; then
fi

docker exec -it ollama ollama $@
