#!/bin/bash

_echo() { echo -e "\e[1m==> $@\e[0m"; }

if ! command -v docker &> /dev/null; then
    echo -e "\e[31;1mERROR\e[0m: docker is not installed"
    exit 1
fi


_echo "Pulling ollama/ollama:rocm ..."
docker pull ollama/ollama:rocm

_echo "Stopping ollama ..."
docker stop ollama

_echo "Updating ollama ..."
docker rm ollama
docker run -d \
    --device /dev/kfd \
    --device /dev/dri \
    -v ollama:/root/.ollama \
    -p 11434:11434 \
    -e OLLAMA_VULKAN=1 \
    -e HSA_OVERRIDE_GFX_VERSION=10.3.0 \
    --name ollama \
    --restart always \
    ollama/ollama:rocm

_echo "Done"
