#!/bin/bash

WEBUI_CONFIG="$HOME/.config/webui-path.conf"

_echo() { echo -e "\e[1m==> $@\e[0m"; }

if ! command -v docker &> /dev/null; then
    echo -e "\e[31;1mERROR\e[0m: docker is not installed"
    exit 1
fi


if test -f "$WEBUI_CONFIG"; then
    STORAGE_LOC="$(cat $WEBUI_CONFIG)"
    _echo "Loading config..."
    echo "Storage location: $STORAGE_LOC"
else
    STORAGE_LOC="$1"

    if test -z "$1"; then
        echo -e "\e[31;1mERROR\e[0m: please, specify a directory for Open WebUI data\n"
        echo -e "\e[1mUsage\e[0m:\n  $0 <directory>"
        exit 1
    fi
fi


if ! test -d "$STORAGE_LOC"; then
    _echo "Creating Open WebUI files..."
    mkdir -p "$STORAGE_LOC"
fi


if ! test -f "$WEBUI_CONFIG"; then
    echo -e "\e[1mNOTE\e[0m: the path will be remembered. To reset, remove the following file:"
    echo -e "    ${WEBUI_CONFIG/$HOME/\~}\n"
    echo "$STORAGE_LOC" > $WEBUI_CONFIG
fi

_echo "Pulling ghcr.io/open-webui/open-webui ...\e[0m"
docker pull ghcr.io/open-webui/open-webui:main

_echo "Stopping open-webui ..."
docker stop open-webui

_echo "Updating container ..."
docker rm open-webui
docker run -d -p 3000:8080 \
	--add-host=host.docker.internal:host-gateway \
	-v $STORAGE_LOC:/app/backend/data \
	-e WEBUI_AUTH=False \
	--name open-webui \
	--restart always \
	ghcr.io/open-webui/open-webui:main

_echo "Done"
